### ISSUE TITLE
Exercise 2.2

### ISSUE THREAD

**Issue by masterxlp** [diegoalejogm/Reinforcement-Learning#4]
The result of action-value estimates maybe error. Sample-average action-value estimate is used to estimate it.

**Comment by diegoalejogm** [comment]
Can you more concretely explain what you mean?

**Comment by masterxlp** [comment]
in book, the author use Q_t(a) = (sum of rewards when a taken prior to t) / (numer of times a taken prior to t), so, when t = 4, Q_4(a_1) = (1 * 1) / 1 = 1, and Q_4(a_2) = (1 * 1 + 2 * 1) / (1+1) = 3 / 2, right?

**Comment by masterxlp** [comment]
Exercise 2.4 don't exist, can you store it again? Thank you!

**Comment by diegoalejogm** [comment]
You are correct. Thanks for spotting it out. I had incorrectly calculated the Q-values with the sum of the previous scores, and forgot to divide them in order to get the average instead. 

I have submitted a fix [here](https://github.com/diegoalejogm/Reinforcement-Learning/blob/master/2.%20Multi-Armed%20Bandits/README.md)

**Comment by diegoalejogm** [comment]
Exercise 2.4 solution is found as a link in the markdown file.
You can directly access the solution [here](https://github.com/diegoalejogm/Reinforcement-Learning/blob/master/2.%20Multi-Armed%20Bandits/2.4.pdf)

**Comment by diegoalejogm** [comment]
Closing this issue. Feel free to re-open if something is not clear
